Collections/Collections/urls.py
from django.contrib import admin
from django.urls import path, include
from collection import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from collection import urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('collection/',include('collection.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Collections/collection/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from collection import views
app_name='collection'
urlpatterns=[
    path('',views.index,name='index'),
    path('collection-detail/<int:pk>/',views.collectionDetailView,name='collection_detail'),
    path('collection-create/',views.collectionCreateView,name='collection_create'),
    path('collection-update/<int:pk>/',views.collectionUpdateView,name='collection_update'),
    path('collection-delete/<int:pk>/',views.collectionDeleteView,name='collection_delete'),
    path('<int:collection_id>/item-detail/<int:pk>/',views.itemDetailView,name='item_detail'),
    path('<int:collection_id>/item-create/',views.itemCreateView,name='item_create'),
    path('<int:collection_id>/item-update/<int:pk>/',views.itemUpdateView,name='item_update'),
    path('<int:collection_id>/item-delete/<int:pk>/',views.itemDeleteView,name='item_delete'),
    path('collection-search/',views.collectionSearchView,name="collection_search"),
    path('logout/',views.user_logout,name='logout'),
    path('login/',views.user_login,name='login'),
    path('register/',views.register,name='register'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Collections/collection/models.py
from django.db import models
from django.urls import reverse
from django.db.models import Q
from django import forms
from django.contrib.auth.models import User
# Create your models here.
class CollectionQuerySet(models.QuerySet):
    
    def search(self, query,user):
        
        lookups = (Q(user=user) &
            (Q(name__icontains=query)|Q(items__item_name__icontains=query))) 
        print(lookups)                  
        return self.filter(lookups).distinct()

class CollectionManager(models.Manager):
    def search(self, query, user):
        return self.get_queryset().search(query, user)

    def get_queryset(self):
        return CollectionQuerySet(self.model, using=self._db)


class CollectionModel(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE,related_name='collections')
    name = models.CharField(max_length=50)
    objects = CollectionManager()
    def get_absolute_url(self):
        return reverse("collection:collection_detail", kwargs={"pk": self.pk})
    
    def __str__(self):
        return self.name

class CollectionItemModel(models.Model):    
    collecttion_name = models.ForeignKey('CollectionModel',on_delete=models.CASCADE,related_name="items")
    item_name = models.CharField(max_length=100)
    item_url = models.URLField()
    item_image = models.ImageField(upload_to='photos',blank=True, null=True)

    def __str__(self):
        return self.item_name

Collections/collection/forms.py
from django import forms  
from collection.models import CollectionModel,CollectionItemModel
from django.forms import modelform_factory
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class CollectionModelForm(forms.ModelForm):
    class Meta:  
        model = CollectionModel  
        fields = ('name',)
        


class CollectionItemModelForm(forms.ModelForm):
    class Meta:  
        model = CollectionItemModel 
        fields =  ('item_name','item_url','item_image')

Collections/collection/views.py
from django.shortcuts import render, redirect, get_object_or_404
from collection.models import CollectionModel, CollectionItemModel
from .forms import CollectionItemModelForm, CollectionModelForm, UserForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.conf import settings
from django.urls import reverse
# Create your views here.
def index(request):
    if request.user.is_authenticated:
        collection_list = CollectionModel.objects.filter(user=request.user)
    else:
        collection_list = {}
    print(request.user)
    return render(request,"collection/index.html",{"collection_list":collection_list})

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('collection:index'))


def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        
        # Check to see both forms are valid
        if user_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
           

            # Now save model
            

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'collection/register.html',
                          {'user_form':user_form,                           
                           'registered':registered})


def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'collection/login.html', {})
@login_required
def collectionDetailView(request,pk):
    collection = CollectionModel.objects.get(pk=pk)
    collection_items = collection.items.all()
    return render(request,"collection/collection_detail.html",
        {
            "collection":collection,
            "collection_items":collection_items,
        }
    )
@login_required
def collectionSearchView(request):
    method_dict = request.GET
    query = method_dict.get('q', None) # method_dict['q']
    
    if query is not None:
        #collection_list = CollectionModel.objects.filter(name__icontains=query)
        collection_list = CollectionModel.objects.search(query,request.user.id)
        return render(request,"collection/collection_search.html",{"collection_list":collection_list})
    return render(request,"collection/collection_search.html",{"collection_list":None})

@login_required
def collectionCreateView(request):
    if request.method == "POST":
        form = CollectionModelForm(request.POST)
        if form.is_valid():
            collection = form.save(commit=False)
            print(collection)
            collection.user = request.user
            collection.save()
            return redirect('collection:index')
    else:
        form = CollectionModelForm()
    return render(request, 'collection/collection_create.html', {'form': form})

@login_required
def collectionUpdateView(request,pk):
    collection = get_object_or_404(CollectionModel, pk = pk) 
    form = CollectionModelForm(request.POST or None, instance=collection)
    if form.is_valid(): 
        form.save() 
        return redirect('collection:collection_detail',pk=pk)
    return render(request,'collection/collection_create.html',{"form":form}) 

@login_required
def collectionDeleteView(request,pk):
    obj = get_object_or_404(CollectionModel, pk = pk) 
  
  
    if request.method =="POST": 
        # delete object 
        obj.delete() 
        # after deleting redirect to  
        # home page 
        return redirect("collection:index") 
  
    return render(request, "collection/collection_delete.html", {}) 

@login_required
def itemDetailView(request,pk,collection_id):
    item = CollectionItemModel.objects.get(pk=pk)
    
    return render(request,"collection/item_detail.html",{"item":item,"media_url":settings.MEDIA_URL})
    

@login_required
def itemCreateView(request,collection_id):
    if request.method == "POST":
        form = CollectionItemModelForm(request.POST, request.FILES or None)
        if form.is_valid():
            
            item = form.save(commit=False)
            item.collecttion_name_id = collection_id            
            item.save()
            return redirect('collection:index')
    else:
        form = CollectionItemModelForm()
    return render(request,"collection/item_create.html",{"form":form})

@login_required
def itemUpdateView(request,pk,collection_id):
    item = get_object_or_404(CollectionItemModel, pk = pk) 
    form = CollectionItemModelForm(request.POST or None, request.FILES or None, instance=item)
    if form.is_valid(): 
        item = form.save(commit=False)
        item.collecttion_name_id = collection_id
        item.save()
        return redirect('collection:item_detail',pk=pk,collection_id=collection_id)
    return render(request,'collection/item_create.html',{"form":form})

@login_required
def itemDeleteView(request,pk,collection_id):
    obj = get_object_or_404(CollectionItemModel, pk = pk) 
    
  
    if request.method =="POST": 
        # delete object 
        obj.delete() 
        # after deleting redirect to  
        # home page 
        return redirect("collection:index") 
  
    return render(request, "collection/item_delete.html", {}) 

Collections/templates/collection/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>
            {% block title_block %}

            {% endblock %}
        </title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <style>
        div.item-detail{
            float: left;
            width: 30%;
            padding: 10px;
            margin: 5px;
            height: 300px;
            text-align: center;
        }
    </style>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-1">
            <div class="container">
                <div class="navbar-nav mr-auto">
                    <a class="navbar-brand" href="{% url 'collection:index' %}">Your Collections</a>
                    <a class="nav-item nav-link" href="#}"></a>
                    
                </div>

                {% if user.is_authenticated %}
                <div class="text-right ml-auto">
                    <form method="GET" action="{% url 'collection:collection_search' %}" class="form-inline mr-auto float-right">
                        <input type="text" class="form-control mb-2 mr-sm-2 " name="q" placeholder="collection name" value="{{request.GET.q}}">
                        <input type="hidden" name="user" value="{{request.user}}"/>
                        <input type="submit" class="btn btn-dark btn btn-outline-success" 
                        value="SEARCH">
                    </form>
                </div>
                
                    <a href="{% url 'collection:logout' %}">Logout</a>
                {% else %}
                    <a href="{% url 'collection:login' %}">Login</a>
                    <a href="{% url 'collection:register' %}">Register</a>
                {% endif %}
            </div>
        </nav>       

        {% block body_block %}


        {% endblock %}
    </body>
</html>

Collections/templates/collection/collection_create.html
{% extends 'collection/base.html' %}

{% block title_block %}
    {% if form.instance.pk %}
        Update Collectiom
    {% else %}
        Create collection
    {% endif %}
{% endblock %}

{% block body_block %}

    <div>
        <form method="POST" style="text-align: center;">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="SUBMIT" class="btn btn-primary btn-lg">
        </form>
    </div>

{% endblock %}

Collections/templates/collection/collection_delete.html
{% extends 'collection/base.html' %}

{% block title_block %}
    Delete Collection
{% endblock %}

{% block body_block %}

    <form method="POST" style="text-align: center;"> 
    <!-- Security token by Django -->
        {% csrf_token %} 
        <p><h1>Are you want to delete this Collection ? </h1></p>
        <input type="submit" value="Yes" class="btn btn-danger btn-lg"/>
        <a href="/" class="btn btn-success btn-lg">Cancel </a>
    </form> 

{% endblock %}

Collections/templates/collection/collection_detail.html
{% extends 'collection/base.html' %}

{% block title_block %}
    {{collection.name}}
{% endblock %}

{% block body_block %}
    <div class="container" style="text-align: center;">
            
        <a href="{% url 'collection:item_create' collection_id=collection.id %}" class="btn btn-primary">
            Add Item
        </a>
        
    </div>
    {% if collection_items %}
        
        <div class="container" style="text-align: center;">
            <div class="row" style="text-align: center;">
            {% for item in collection_items %}
                
            <div class="col-lg-3 col-md-6 col-sm-12 m-2 bg-light" style="text-align: center; margin: 10px; padding: 15px;">

                    <h1><a href="{% url 'collection:item_detail' collection_id=collection.id pk=item.id %}">{{item.item_name}}</a></h1>
                    {% if item.item_image %}
                        <img src="{{item.item_image.url|default_if_none:'#'}}" style="max-width:100%;
                        max-height:100%; margin-bottom: 5px;">
                    {% endif %}
                    
                    <a href="{% url 'collection:item_update' collection_id=collection.id pk=item.id %}" class="btn btn-warning btn-lg">
                        Update
                    </a>
                    <a href="{% url 'collection:item_delete' collection_id=collection.id pk=item.id %}" class="btn btn-danger btn-lg">
                        Delete
                    </a>
                </div>
                   
            {% endfor %}
            </div>
        </div>
            
        
    {% else %}
        <div class="jumbotron" style="text-align: center; color:red">
            <h1> No items in {{collection.name}} </h1>
        </div>
    {% endif %}

{% endblock %}

Collections/templates/collection/collection_search.html
{% extends 'collection/base.html' %}

{% block title_block %}
    Collections
{% endblock %}

{% block body_block %}
    {% if not request.GET.q == '' %}
        <div class="row">
            <div class="col-md-8 col-sm-12 ml-auto mr-auto">
                <h1> Search for <b>{{request.GET.q}}</b></h1>
            </div>
        </div>
    {% endif %}

    {% if collection_list %}
        <div class="container" style="text-align: center;">
            {% for collection in collection_list %}
            
                <div class="jumbotron item-detail" style="text-align: center; margin:10px;">
                    <h1><a href="{% url 'collection:collection_detail' pk=collection.id %}">{{collection.name}}</a></h1>
                    <p><a href="{% url 'collection:collection_update' pk=collection.id %}" class="btn btn-warning btn-lg">Update</a></p>
                    <a href="{% url 'collection:collection_delete' pk=collection.id %}" class="btn btn-danger btn-lg">Delete</a>
                </div>
            
            {% endfor %}
        </div>
    {% else %}
        <div class="jumbotron" style="text-align: center; color:red">
            No Collections found
        </div>
    {% endif %}

{% endblock %}

Collections/templates/collection/collection_update.html
{% extends 'collection/base.html' %}

{% block title_block %}
    Update Collection
{% endblock %}

{% block body_block %}
    <div class="jumbotron">
        <form method="POST" style="text-align: center;" class="form-group"> 
        <!-- Security token by Django -->
            {% csrf_token %} 
            {{ form.as_p }}
            <p><input type="submit" value="Yes" class="btn btn-danger btn-lg"/> </p>
            
        </form> 
    </div>
{% endblock %}

Collections/templates/collection/index.html
{% extends 'collection/base.html' %}

{% block title_block %}
    Collections
{% endblock %}

{% block body_block %}
    
    {% if user.is_authenticated %}
    <div class="container-fluid" style="text-align: center;">
        
        <a href="{% url 'collection:collection_create' %}" class="btn btn-primary">
            Add Collection
        </a>
        
    </div>
    {% endif %}

    {% if collection_list and user.is_authenticated %}
        <div class="container" style="text-align: center;">
            <div class="row" style="text-align: center;">
                {% for collection in collection_list %}
                
                <div class="col-lg-3 col-md-6 col-sm-12 m-2 bg-light" style="text-align: center; margin: 10px; padding: 15px;">
                        <h1><a href="{% url 'collection:collection_detail' pk=collection.id %}">{{collection.name}}</a></h1>
                        <p><a href="{% url 'collection:collection_update' pk=collection.id %}" class="btn btn-warning btn-lg">Update</a></p>
                        <a href="{% url 'collection:collection_delete' pk=collection.id %}" class="btn btn-danger btn-lg">Delete</a>
                    </div>
                
                {% endfor %}
            </div>
        </div>
    {% elif user.is_authenticated %}
        <div class="jumbotron" style="text-align: center; color:red">
            No Collections
        </div>
    {% else %}
        <div class="jumbotron" style="text-align: center; color:red">
            Please login to view your collections
        </div>
    {% endif %}
{% endblock %}

Collections/templates/collection/item_create.html
{% extends 'collection/base.html' %}

{% block title_block %}
    {% if form.instance.pk %}
        Update Item
    {% else %}
        Create Item
    {% endif %}
{% endblock %}

{% block body_block %}

    <div>
        <form method="POST" style="text-align: center;" enctype='multipart/form-data'>
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="SUBMIT" class="btn btn-primary btn-lg">
        </form>
    </div>


{% endblock %}

Collections/templates/collection/item_delete.html
{% extends 'collection/base.html' %}

{% block title_block %}
    Delete Item
{% endblock %}

{% block body_block %}

    <form method="POST" style="text-align: center;"> 
    <!-- Security token by Django -->
        {% csrf_token %} 
        <p><h1>Are you want to delete this item ? </h1></p>
        <p><input type="submit" value="Yes" class="btn btn-danger btn-lg"/> </p>
        <p><a href="/" class="btn btn-success btn-lg">Cancel </a> </p>
    </form> 

{% endblock %}

Collections/templates/collection/item_detail.html
{% extends 'collection/base.html' %}

{% block title_block %}
    {{item.name}}
{% endblock %}

{% block body_block %}

    <div class="container" style="text-align: center;">
        <div class="jumbotron">
            <h1 class="display-3">{{item.item_name}}</h1>
            {% if item.item_image %}
                <img src="{{item.item_image.url|default_if_none:'#'}}">
            {% endif %}
            <p class="lead"><a href="{{item.item_url}}">{{item.item_url}}</a></p>
            <hr class="my-2">
            
            <p class="lead">
                

            </p>
        </div>
    </div>
    
{% endblock %}

Collections/templates/collection/item_update.html
{% extends 'collection/base.html' %}

{% block title_block %}
    Update Item
{% endblock %}

{% block body_block %}

    <form method="POST" style="text-align: center;" enctype='multipart/form-data'> 
    <!-- Security token by Django -->
        {% csrf_token %} 
        {{ form.as_p }}
        <p><input type="submit" value="Yes" class="btn btn-danger btn-lg"/> </p>
        
    </form> 

{% endblock %}

Collections/templates/collection/login.html
{% extends 'collection/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'collection:login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

Collections/templates/collection/register.html
{% extends "collection/base.html" %}
{% load static %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}